# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "c0eaefabeeae26590d493a2a27682e63"
name = "squid"
handle = "squid-2"
application_url = "https://shopify-squid-app.vercel.app"
embedded = false

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = false

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "https://shopify-squid-app.vercel.app/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "https://shopify-squid-app.vercel.app/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app_subscriptions/update" ]
  uri = "https://shopify-squid-app.vercel.app/webhooks/billing"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "https://shopify-squid-app.vercel.app/webhooks/billing"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_shop,write_shop,read_billing,write_billing"

[auth]
redirect_urls = [
  "https://shopify-squid-app.vercel.app/auth/callback",
  "https://shopify-squid-app.vercel.app/auth/shopify/callback",
  "https://shopify-squid-app.vercel.app/api/auth/callback"
]

[[extensions]]
type = "navigation"
name = "Dashboard"
url = "/dashboard"

[[extensions]]
type = "navigation"
name = "Main Site"
url = "/home"

[pos]
embedded = false
